name: Fetch Weather

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Call OpenWeather API
        run: |
          curl "https://api.openweathermap.org/data/2.5/weather?lat=-34.6037&lon=-58.3816&appid=${{ secrets.OPENWEATHER_API_KEY }}"